#! /bin/bash

# Where is our server to test?
SOTD_SERVER=http://127.0.0.1
SOTD_PORT=5000
SOTD=$SOTD_SERVER:$SOTD_PORT

# How many -v's to give to curl
#VERBOSITY="-v"

# Fix up strange output issues
TEST() {
    echo ; echo $1 ; shift
}

# Get a fresh database first off.
mongo sot_test --eval "db.dropDatabase()"

# Base url, should give us a basic summary of sotd itself
#    -H "Content-Type: application/json" \
TEST "summary"
curl $VERBOSITY -X GET \
     $SOTD/

# Get a list of all available collections
# TODO: later, list of objs/docs in each collection
TEST "get all collections"
curl $VERBOSITY -X GET $SOTD/collections

TEST "create two new collections"
#         {"name": "magazines"} ]'\

curl $VERBOSITY -X POST \
     -H "Content-Type: application/json" \
     -d '[ {"name": "books", "description": "my books"}]' \
    $SOTD/collections

TEST "get a field"
#     -d '[ {"name": "books", "description": "my books"}]' \
curl $VERBOSITY -X GET \
     -H "Content-Type: application/json" \
    $SOTD/collections/books/items/hero/fields/name

# TEST "debug query inline"
# curl $VERBOSITy -X GET \
#      "$SOTD/query?q=memory&fq=inStock:true"

# TEST "debug query json"
# curl $VERBOSITY -X GET \
#      $SOTD/query -d '
# {
#   "query" : "memory",
#   "filter" : "inStock:true"
# }'


## END OF LINE ##
